### ISSUE TITLE
Problem with many samples

### ISSUE THREAD

**Issue by AmirSinaRZ** [alexei-frolo/WaveformSeekBar#7]
When i extract samples from song and pass to wave form seekbar ui freeze for seconds.
How can i fix it?
![preview](https://s2.uupload.ir/files/screenshot_2023-01-12-19-26-56-204_ir.amirsina.lyricm_xmnl.jpg)

**Comment by artsmvch** [comment]
Can you please share the sample with me? You can write numbers, separated by comma, into a txt file and attach this file here.

**Comment by AmirSinaRZ** [comment]
Thanks for reply.
This is my samples :
https://easyupload.io/dqkptw
I use this library to get samples as list then do this (https://github.com/lincollincol/Amplituda)
`samps =  amplitudesData.stream().filter(t -> t != null).mapToInt(t -> t).toArray();`

**Comment by AmirSinaRZ** [comment]
I don't know where this lag comes from

**Comment by AmirSinaRZ** [comment]
Problem was from Amplituda.
I create sample in background then set sample.
